# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: CMake

on: [push]

permissions:
  contents: read
    
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
    - name: Checkout project and submodules
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Generate
      run: cmake -B build -S . -D CMAKE_CXX_FLAGS="-fprofile-arcs -ftest-coverage"

    - name: Build
      run: cmake --build build

    - name: Test
      run: ctest --test-dir build --no-tests=error -C debug
